# Generated by Django 5.1 on 2024-09-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DynamicSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("value", models.TextField(blank=True)),
                (
                    "description",
                    models.CharField(
                        blank=True, default=None, max_length=1000, null=True
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("name", "category")},
            },
        ),
    ]
